### ISSUE TITLE
[META] add tests

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/reference#27]
Here's a list of test to write:
- [x] create reference field
- [x] select entity type on the settings form
- [ ] entity type select disabled after field has data
- [ ] autocomplete callback reads field settings properly
- [ ] autocomplete respects bundle
- [ ] autocomplete respects status
- [ ] status checkbox disabled on instance settings for entity type that doesn't define status key
- [ ] feeding a bad id number
- [ ] changing an existing field value
- [ ] display value on entity view
- [ ] required field cannot be blank
- [ ] default value entered in the instance form

**Comment by jenlampton** [comment]
As we talked about today at BackdropLIVE, @hosef plans to steal the tests from the D7 contrib modules, and adapt those as necessary.
