### ISSUE TITLE
[meta] Core changes needed

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop-contrib/reference#36]
The following changes need to be made to core in order for things to work properly without the shims that are currently in place in the code.

- [ ] Define label and status entity keys in core: https://github.com/backdrop/backdrop-issues/issues/3103
- [ ] Handle file stream wrappers since l() and url() currently don't: https://github.com/backdrop/backdrop-issues/issues/2300
- [ ] Add options array for files: https://github.com/backdrop/backdrop-issues/issues/2299
- [ ] Add view function to the entity api: https://github.com/backdrop/backdrop-issues/issues/1739

**Comment by jenlampton** [comment]
I've copied this meta into https://github.com/backdrop/backdrop-issues/issues/1301 (since they are core issues, we wanted them in the core queue) so closing this as dupe
