### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/reference#4]
In progress:

- [ ] Views integration

Things to do:

- [ ] reverse views relationship
- [ ] Why is the echo in backdrop_json_output not disabling the theme?
- [ ] validate that the text matches the title of the entity with the entered id
- [ ] figure out proper way to set widget title so it isn't repeated with multiple values.
- [ ] make sure that a default value can be set in the field instance settings form
- [ ] update field validation to test that the referenced entity meets current restrictions
- [ ] access check on autocomplete callback to check that user has ability to edit the field
- [ ] add access check to the entity info so user can only select content they can access
- [ ] hide the numeric id from the user after autocomplete select
- [ ] autocomplete to get entity labels that start with the typed text before just containing
- [ ] additional field formatter to display rendered entity
- [ ] multilingual support for label autocomplete

Test to write:

- [ ] create reference field
- [ ] select entity type on the settings form
- [ ] entity type select disabled after field has data
- [ ] autocomplete callback reads field settings properly
- [ ] autocomplete respects bundle
- [ ] autocomplete respects status
- [ ] feeding a bad id number
- [ ] changing an existing field value
- [ ] display value on entity view
- [ ] required field cannot be blank
- [ ] default value entered in the instance form

To merge into core:

- [ ] write tests
- [ ] patch core modules to provide their label and status properties in their entity info
- [ ] remove then-unneeded reference_entity_info_alter() function

Possible core changes:

- [ ] add bundles for file entities
- [ ] add plural for bundle labels
- [ ] replace references provided by other core modules, such as taxonomy tags and other term refs
- [ ] upgrade path from taxonomy reference modules
- [ ] upgrade path from contrib references to reference
- [ ] standardized autocomplete widget
- [ ] file key for includes in hook_field_widget_info and hook_field_formatter_info
- [ ] file key for includes in hook_field_info

**Comment by docwilmot** [comment]
Make it easier to know how far to go.

**Comment by xmacinfo** [comment]
Is it also possible to include:
- Reverse field relationship (a field that would display all nodes parent automatically), without requiring a view?

**Comment by herbdool** [comment]
Can we add hooks to this list so that the behaviour and selection of the field can be extended by other modules? (Much like in entity reference, references).

**Comment by mikemccaffrey** [comment]
@herbdool We can add hooks where folks are finding that they need them. However, for the most part, it seems desirable for other modules to just define their own field formatters and selection widgets if they are looking for functionality that differs from the default behavior.

If anyone thinks that we should provide a hook in a particular location, can you please open a issue for just that?
